.Include "tn2313def.inc"

;Задание символических имен регистрам
.def temp = r29

// Port initialization
		ldi temp,	$ff			;
		out ddrb,	temp		;
		out ddrd,	temp		;

		out spl, 	temp		;Иницмализация стека

		ldi r16, 0x00
		ldi r17, 0x01
		ldi r18, 0x03
		ldi r19, 0x05
		ldi r20, 0x08
		ldi r21, 0x0C
		ldi r22, 0x10
		ldi r23, 0x15
		ldi r24, 0x1A
		ldi r25, 0x20
		ldi r26, 0x25
		ldi r27, 0x2C
		ldi r28, 0x32
		ldi r29, 0x39
		ldi r30, 0x40
		ldi r31, 0x46

		mov r0, r16
		mov r1, r17
		mov r2, r18
		mov r3, r19
		mov r4, r20
		mov r5, r21
		mov r6, r22
		mov r7, r23
		mov r8, r24
		mov r9, r25
		mov r10, r26
		mov r11, r27
		mov r12, r28
		mov r13, r29
		mov r14, r30
		mov r15, r31

		ldi r16, 0x4D
		ldi r17, 0x53
		ldi r18, 0x5A
		ldi r19, 0x5F
		ldi r20, 0x65
		ldi r21, 0x6A
		ldi r22, 0x6F
		ldi r23, 0x73
		ldi r24, 0x77
		ldi r25, 0x7A
		ldi r26, 0x7C
		ldi r27, 0x7E
		ldi r28, 0x7F
		clr r29
		clr r30
		clr r31



Start:	
		ldi temp, 	0
		out portb, 	temp
		ldi temp, 	0
		out portb, 	temp
		ldi temp, 	1
		out portb, 	temp
		ldi temp, 	2
		out portb, 	temp
		ldi temp, 	3
		out portb, 	temp
		ldi temp, 	4
		out portb, 	temp
		ldi temp, 	5
		out portb, 	temp
		ldi temp, 	7
		out portb, 	temp
		ldi temp, 	9
		out portb, 	temp
		ldi temp, 	11
		out portb, 	temp
		ldi temp, 	13
		out portb, 	temp
		ldi temp, 	16
		out portb, 	temp
		ldi temp, 	18
		out portb, 	temp
		ldi temp, 	21
		out portb, 	temp
		ldi temp, 	24
		out portb, 	temp
		ldi temp, 	28
		out portb, 	temp
		ldi temp, 	31
		out portb, 	temp
		ldi temp, 	35
		out portb, 	temp
		ldi temp, 	38
		out portb, 	temp
		ldi temp, 	42
		out portb, 	temp
		ldi temp, 	46
		out portb, 	temp
		ldi temp, 	50
		out portb, 	temp
		ldi temp, 	55
		out portb, 	temp
		ldi temp, 	59
		out portb, 	temp
		ldi temp, 	64
		out portb, 	temp
		ldi temp, 	68
		out portb, 	temp
		ldi temp, 	73
		out portb, 	temp
		ldi temp, 	78
		out portb, 	temp
		ldi temp, 	83
		out portb, 	temp
		ldi temp, 	88
		out portb, 	temp
		ldi temp, 	93
		out portb, 	temp
		ldi temp, 	98
		out portb, 	temp
		ldi temp, 	104
		out portb, 	temp
		ldi temp, 	109
		out portb, 	temp
		ldi temp, 	114
		out portb, 	temp
		ldi temp, 	119
		out portb, 	temp
		ldi temp, 	125
		out portb, 	temp
		ldi temp, 	130
		out portb, 	temp
		ldi temp, 	136
		out portb, 	temp
		ldi temp, 	141
		out portb, 	temp
		ldi temp, 	146
		out portb, 	temp
		ldi temp, 	151
		out portb, 	temp
		ldi temp, 	157
		out portb, 	temp
		ldi temp, 	162
		out portb, 	temp
		ldi temp, 	167
		out portb, 	temp
		ldi temp, 	172
		out portb, 	temp
		ldi temp, 	177
		out portb, 	temp
		ldi temp, 	182
		out portb, 	temp
		ldi temp, 	187
		out portb, 	temp
		ldi temp, 	191
		out portb, 	temp
		ldi temp, 	196
		out portb, 	temp
		ldi temp, 	200
		out portb, 	temp
		ldi temp, 	205
		out portb, 	temp
		ldi temp, 	209
		out portb, 	temp
		ldi temp, 	213
		out portb, 	temp
		ldi temp, 	217
		out portb, 	temp
		ldi temp, 	220
		out portb, 	temp
		ldi temp, 	224
		out portb, 	temp
		ldi temp, 	227
		out portb, 	temp
		ldi temp, 	231
		out portb, 	temp
		ldi temp, 	234
		out portb, 	temp
		ldi temp, 	237
		out portb, 	temp
		ldi temp, 	239
		out portb, 	temp
		ldi temp, 	242
		out portb, 	temp
		ldi temp, 	244
		out portb, 	temp
		ldi temp, 	246
		out portb, 	temp
		ldi temp, 	248
		out portb, 	temp
		ldi temp, 	250
		out portb, 	temp
		ldi temp, 	251
		out portb, 	temp
		ldi temp, 	252
		out portb, 	temp
		ldi temp, 	253
		out portb, 	temp
		ldi temp, 	254
		out portb, 	temp
		ldi temp, 	255
		out portb, 	temp
		ldi temp, 	255
		out portb, 	temp

		ldi temp, 	255
		out portb, 	temp

		ldi temp, 	255
		out portb, 	temp
		ldi temp, 	255
		out portb, 	temp
		ldi temp, 	254
		out portb, 	temp
		ldi temp, 	253
		out portb, 	temp
		ldi temp, 	252
		out portb, 	temp
		ldi temp, 	251
		out portb, 	temp
		ldi temp, 	250
		out portb, 	temp
		ldi temp, 	248
		out portb, 	temp
		ldi temp, 	246
		out portb, 	temp
		ldi temp, 	244
		out portb, 	temp
		ldi temp, 	242
		out portb, 	temp
		ldi temp, 	239
		out portb, 	temp
		ldi temp, 	237
		out portb, 	temp
		ldi temp, 	234
		out portb, 	temp
		ldi temp, 	231
		out portb, 	temp
		ldi temp, 	227
		out portb, 	temp
		ldi temp, 	224
		out portb, 	temp
		ldi temp, 	220
		out portb, 	temp
		ldi temp, 	217
		out portb, 	temp
		ldi temp, 	213
		out portb, 	temp
		ldi temp, 	209
		out portb, 	temp
		ldi temp, 	205
		out portb, 	temp
		ldi temp, 	200
		out portb, 	temp
		ldi temp, 	196
		out portb, 	temp
		ldi temp, 	191
		out portb, 	temp
		ldi temp, 	187
		out portb, 	temp
		ldi temp, 	182
		out portb, 	temp
		ldi temp, 	177
		out portb, 	temp
		ldi temp, 	172
		out portb, 	temp
		ldi temp, 	167
		out portb, 	temp
		ldi temp, 	162
		out portb, 	temp
		ldi temp, 	157
		out portb, 	temp
		ldi temp, 	151
		out portb, 	temp
		ldi temp, 	146
		out portb, 	temp
		ldi temp, 	141
		out portb, 	temp
		ldi temp, 	136
		out portb, 	temp
		ldi temp, 	130
		out portb, 	temp
		ldi temp, 	125
		out portb, 	temp
		ldi temp, 	119
		out portb, 	temp
		ldi temp, 	114
		out portb, 	temp
		ldi temp, 	109
		out portb, 	temp
		ldi temp, 	104
		out portb, 	temp
		ldi temp, 	98
		out portb, 	temp
		ldi temp, 	93
		out portb, 	temp
		ldi temp, 	88
		out portb, 	temp
		ldi temp, 	83
		out portb, 	temp
		ldi temp, 	78
		out portb, 	temp
		ldi temp, 	73
		out portb, 	temp
		ldi temp, 	68
		out portb, 	temp
		ldi temp, 	64
		out portb, 	temp
		ldi temp, 	59
		out portb, 	temp
		ldi temp, 	55
		out portb, 	temp
		ldi temp, 	50
		out portb, 	temp
		ldi temp, 	46
		out portb, 	temp
		ldi temp, 	42
		out portb, 	temp
		ldi temp, 	38
		out portb, 	temp
		ldi temp, 	35
		out portb, 	temp
		ldi temp, 	31
		out portb, 	temp
		ldi temp, 	28
		out portb, 	temp
		ldi temp, 	24
		out portb, 	temp
		ldi temp, 	21
		out portb, 	temp
		ldi temp, 	18
		out portb, 	temp
		ldi temp, 	16
		out portb, 	temp
		ldi temp, 	13
		out portb, 	temp
		ldi temp, 	11
		out portb, 	temp
		ldi temp, 	9
		out portb, 	temp
		ldi temp, 	7
		out portb, 	temp
		ldi temp, 	5
		out portb, 	temp
		ldi temp, 	4
		out portb, 	temp
		ldi temp, 	3
		out portb, 	temp
		ldi temp, 	2
		out portb, 	temp
		ldi temp, 	1
		out portb, 	temp
		ldi temp, 	0
		out portb, 	temp
		ldi temp, 	0
		out portb, 	temp


	rjmp Start		;


		
		
		
		
		
				

